FROM node:22-alpine

WORKDIR /app

# Instala dependencias (incluye dev para tsx en dev)
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

COPY . .

ENV NODE_ENV=development
EXPOSE 3000

CMD ["yarn", "dev", "-H", "0.0.0.0"]
